[package]
name = "rs-gdbm"
version = "0.1.0"
authors = ["Jeff Garzik <jeff@bloq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "^1.3.2"
clap = "^2.33.0"
