[package]
name = "rs-gdbm"
version = "0.5.0"
authors = ["Jeff Garzik <jgarzik@pobox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "^1.3"
base64 = "^0.13"
